name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image
on: [push]
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  IMAGE_NAME: "ghcr.io/yaya777o/nginx-sitiazzaria"
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u yaya777o --password-stdin
      - name: stop and remove existing container
        run: docker compose down --rmi all
      - name: start container
        run: docker compose up -d
      - name: view container
        run: docker compose ps
      - name: check container
        run: curl localhost:8080
